### ISSUE TITLE
Burglar Pete's L59 Charmeleon's Fire Spin is buggy (Cinnabar Mansion)

### ISSUE THREAD

**Issue by roukaour** [roukaour/pokecrystal#122]
Not only does it OHKO my L100 Mewtwo, but Charmeleon's HP drops to zero right when it's used.

Its Slash and Crunch behave as expected, doing a small amount of damage, although it still should not outspeed me.

**Comment by FredrIQ** [comment]
How does it OHKO it? "Instantly" (HP-to-zero bug) or an actual OHKO?

**Comment by FredrIQ** [comment]
53f40e8910f991dd9a5eab84131f361e34114964 might fix all of the random weirdness in the battle engine lately. Note that this doesn't fix Speed not working correctly, but should hopefully address everything else (CheckTypeMatchup corrupted the stack which caused several random issues, some of them seemingly nonsensical since the AI uses that function as well).
