### ISSUE TITLE
Base Ability effects on what generation?

### ISSUE THREAD

**Issue by FredrIQ** [roukaour/pokecrystal#15]
I assumed the intention was to base them on how they work in Generation VI. However, 2 (out of 2 applicable) changes so far suggests basing them on Generation V.

* (Oblivious' reference to Taunt was removed, but apparently Taunt didn't exist in 2gen)
* Permaweather
* Infiltrator doesn't bypass Substitute (and was denoted as finished code-wise, and description no longer references Substitute)

So, should one base abilities on 5gen or 6gen? Just checking for consistency.

**Comment by roukaour** [comment]
Those were both oversights on my part. Abilities should be Gen VI. Although I did remove the Taunt reference because the move doesn't exist. And some other descriptions were made less precise because they're consistently phrased that way in canon.

The weather abilities should definitely be limited, since once TMs use a bit array and free up 73 item slots, Heat+Damp+Smooth Rock can be used to extend them to 8 turns.

**Comment by FredrIQ** [comment]
Made a PR -- #16 -- which reverts permaweather. Also found out the issue with wild Pokémon not having their activation abilities run, they don't run NewEnemyMonStatus.
