### ISSUE TITLE
Low battle RAM space

### ISSUE THREAD

**Issue by FredrIQ** [roukaour/pokecrystal#31]
I was going to implement Harvest and Pickup by adding 2 bytes, PlayerUsedItems, EnemyUsedItems that are bitfields of which held items that has been consumed. Thus, not clear the item right away but rather at the end of the battle unless picked up or harvested, but mark it as used up.

One issue with this approach, aside from potential bugs (the alternative, less error-prone way, requires 12 bytes free rather than 2), is the following scenario:
- A uses up Oran Berry
- B uses up Oran Berry
- A's pickup activates, picking up B's Oran Berry
- B can now no longer pickup A's item, because B's Oran Berry overrided the used up item by A when A picked it up

I have no ideas for how this could be solved, other than using the more memory-expensive way of storing used up items outright. However, I don't see 12 bytes free in Battle RAM (only 4 obvious free ones)...

You could get away with only using 6 bytes with a seperate "used up battle items" table (using 4 bits per item, so up to 15 potential consumables in total), but that doesn't seem worth it to me, and you're still missing free bytes.

Suggestions?

Alternatively, you could maybe free up some bytes by storing a few things that ultimately doesn't need 8 bits, together in 4bit nibbles and using swap (the least awkward way to merge information) -- for example, screen counts (which has a limit of 5, or 8 with light clay anyway). Also moving single-bit information into substatus arrays (Minimized comes to mind).

**Comment by roukaour** [comment]
What if you have two bytes, PlayerHarvestableBerry and EnemyHarvestableBerry? When a Pokémon eats a berry it's stored in the appropriate variable. If their opponent has Pickup and no held item, they'll pick up the berry and clear the variable. On later turns, if the Pokémon has Harvest there's a 50% chance for it to take back its berry and clear the variable. And, if a Pokémon is switched out its variable gets cleared.

I think this approach would match the official games, because according to Bulbapedia you wouldn't need a bitfield with flags for every possible item, just space to store both sides' single items.

Harvest: "However, a Pokémon may only have one consumed item (including non-Berries) at a time; if a Pokémon consumes a Berry, obtains another item and consumes it, the original consumed Berry cannot be restored, even if the second item is restored and swapped away."

Pickup: "A Pokémon may only have one consumed item at a time; if a Pokémon consumes an item, obtains another item and consumes it, the original consumed item cannot be collected, even if the second item is collected or restored then swapped away. If the Pokémon obtains another item after consuming an item, Pickup can still collect the old item as long as the Pokémon does not consume the new one."

So in the scenario you describe:

1. B uses Double-Edge.
2. A is damaged and eats their held Oran Berry. AHarvestableBerry = Oran Berry.
3. B's Pickup does not activate because it's already holding an Oran Berry.
4. B is damaged by recoil and eats their held Oran Berry. BHarvestableBerry = Oran Berry.
5. A's Pickup activates and takes B's used-up Oran Berry. BHarvestableBerry = nothing.

Is this not how it would play out in the actual games?

**Comment by FredrIQ** [comment]
The issue is that if you switch out, the item for the Pokémon that switched out is still tied to it, which means that switching out prevents Pickup from snatching that item, at least until the Pokémon comes back into battle again. This is why one needs to track all 6 items.

**Comment by roukaour** [comment]
"switching out prevents Pickup from snatching that item"—that's correct, isn't it? Bulbapedia: "Pickup cannot collect an item if the Pokémon that consumed the item is no longer on the field at the end of the turn, or if the item has already been recovered (such as with Recycle, another Pokémon's Pickup, or Harvest). Pickup cannot collect an item that a Pokémon consumed before switching out, even if it switched back in again before the end of the turn."

Also, the absence of switch-out triggers like U-Turn, Volt Switch, Red Card, and Eject Button simplifies a lot of this logic. Like, "Pickup cannot collect an item that a Pokémon consumed before switching out, even if it switched back in again before the end of the turn"—I can't imagine a scenario where that would happen, since switching out is your sole action for the turn.

**Comment by roukaour** [comment]
As far as I can tell, Harvest isn't an issue either. It's true that "the held Berry is remembered even if it is not restored or if the Pokémon has switched out," but that's still just one berry. If my Exeggutor eats an Oran Berry, switches out, then switches back in, it can still harvest the Oran Berry. But if I switch out to Tropius, who eats a Sitrus Berry, that replaces Oran Berry as the harvestable berry. (And if I switched out to Houndour, who eats a Lum Berry, that wouldn't affect the HarvestableBerry variable at all since Houndour doesn't have Harvest.)

It seems like part of the complexity here is for the sake of double battles, which also don't exist.

**Comment by FredrIQ** [comment]
I am looking at both Bulbapedia and asking people who I've used as sources earlier for exact ability mechanics, and I come to this conclusion myself as a potential scenario:

* Exeggutor munches up an Oran Berry. Harvest doesn't activate
* Exeggutor switches out to Tropius
* Tropius munches up a Sitrus Berry. Harvest doesn't activate
* Tropius switches out to Exeggutor
* Exeggutor's Harvest activates, picking up the Oran Berry
* Exeggutor switches out to Tropius
* Tropius' Harvest activates, picking up the Sitrus berry

**Comment by FredrIQ** [comment]
OK, so I just attempted this in Pokémon Showdown, and items are indeed saved per mon in the manner I described above: http://replay.pokemonshowdown.com/ou-450107460 (turn 6 and 7)

**Comment by roukaour** [comment]
I see. In that case, since all this only applies to Berries, you could save all twelve values in six bytes by subtracting BERRY from the value and saving the low four bits. SECTION "Battle" has at least six free bytes: [2](https://github.com/roukaour/pokecrystal/blob/master/wram.asm#L390) + [2](https://github.com/roukaour/pokecrystal/blob/master/wram.asm#L400) + [1](https://github.com/roukaour/pokecrystal/blob/master/wram.asm#L606) + [2](https://github.com/roukaour/pokecrystal/blob/master/wram.asm#L625).
