### ISSUE TITLE
Goals for 3.0.0

### ISSUE THREAD

**Issue by roukaour** [roukaour/pokecrystal#34]
**Miscellaneous:**

* Copy the HG/SS Mahogany Town Team Rocket Souvenir Shop
* Sell some unique items in the post−Team Rocket Souvenir Shop
* Change what the Goldenrod Harbor merchant sells after determining the Battle Tower BP merchants
* Also use the Shamouti merchant for unique items

**Battle mechanics:**

* Abilities (25 of 151 left)
* Held item effects
* Move effects
* Generate wild and NPC Pokémon
* Generate Battle Tower Pokémon
* New move animations (23 of 54 left)
* Bug fixes (see other issues)

**Other mechanics:**

* Update breeding with the new data structure (engine/breeding/egg.asm and event/daycare.asm)
* Update breeding to Gen VII, including Destiny Knot, Everstone, and Oval Charm effects
* Wild Ghosts and the SilphScope2
* Variety Channel on radio
* Bottle Caps for Hyper Training found by fishing
* Faster Bicycle
* Colored party Pokémon icons

**Events:**

* Soul House + Radio Tower event to get Expn Card
* Battle Tower merchants selling items for BP
* Six Hyper Trainers for each stat in Battle Tower 2F
* Lost Pikablu (Marill) in Noisy Forest
* Get Kanto starters from Prof. Ivy, Prof. Oak, and Blue
* Celadon University Hyper Test with Dragon Rage Magikarp as a reward

**Characters:**

* Cheryl in Murky Swamp
* Marley in Quiet Cave 5F
* Buck in Mt. Moon B2F
* Riley in Dim Cave B3F
* Mira in Scary Cave 1F
* Anabel in Noisy Forest
* Candela in Fire Island peak
* Blance in Ice Island peak
* Spark in Lightning Island peak
* Caitlin and Darach in Beautiful Beach villa
* Looker in Shamouti Hotel room (not S.S. Aqua)
* Trendy phrase guy in Shamouti Hotel lobby
* Flannery somewhere (Safari Zone?)
* Skyla somewhere (Lighthouse roof?)
* Lawrence in Shrine Ruins (not Victory Road)
* Prof. Ivy in Shamouti Island (gives a starter)
* Imakuni in Celadon University
* Inver in Route 16 house
* Gourmet Maniac in Route 32 Coast house
* Ore Maniac in Shamouti Tunnel
* Body Slam tutor in Warm Beach house
* Substitute tutor in Dim Cave
* Sucker Punch tutor in Scary Cave
* Pay Day tutor in Goldenrod Game Corner

**Maps:**

Maps need NPCs, trainers (with [dialog](https://docs.google.com/document/d/1_IDuWAP-QBRC5l4grKZKKlfWKQ2BjC2Yo0aynmli1Ac/view)), visible and hidden items, wild Pokémon, and unique wild moves.

* Route 11 (and other expanded Kanto routes)
* Route 16
* Route 19+20+21 (extra HG/SS trainers)
* Lucky Island (wild Chansey and Togepi/Togetic, Lucky Egg)
* Uraga Channel
* Scary Cave
* Murky Swamp
* Union Cave B1F South
* Quiet Cave
* Celadon Hotel (just items left)
* Celadon University
* Mt. Moon (fossils)
* Dim Cave (Facade TM)
* Soul House
* Lavender Radio Tower
* Shamouti Island (outdoor market instead of Mart)
* Shamouti Hotel (haunted room)
* Shamouti Tunnel
* Warm Beach
* Rocky Beach
* Noisy Forest (U-Turn TM, Big Mushroom, BalmMushroom)
* Shrine Ruins
* Fire/Ice/Lightning Islands
* Union Cave 1F (HGSS layout)

**Comment by FredrIQ** [comment]
Wasn't 2.0 released just 2 weeks ago? Is it worth bumping the version number already? People have already had to restart once after all. Isn't it better to have a 2.4 with everything mentioned minus bag expansion? Or is there not room in the save for it?

**Comment by roukaour** [comment]
2.0 was a month ago, and I don't expect 3.0 to be ready for a least another month. The abilities will take time, I'm designing the new maps, and Mmmmmm said he can hopefully finish some new music in a month or so.

Things that will break saves: refactoring TMs (modifies Bag data structure), permanent HM moves (adding an event/flag for every tree/rock/whirlpool will exceed my reserved ones), and adding personality values for Pokémon.

**Comment by FredrIQ** [comment]
Ah, didn't realize that there wasn't enough event flags. Combined with the other changes, and the fact that 2.0 was longer ago than I thought, and fair enough.

**Comment by FredrIQ** [comment]
For the TM change, how about making TMs and HMs be part of a TM case in FRLG? While I generally disliked that change (since I had to first go to key items and find the case), the reason I am making this suggestion is that it allows making a custom interface for it that shows all relevant move data (similar to the Moves menu interface in the Pokémon list)

**Comment by roukaour** [comment]
TM case: I'll think about it.

TM balls are blue because yellow idn't in the palette, and coloring both halves the same yellowish-white looked bland.

**Comment by FredrIQ** [comment]
Trainer battles load an enemy party similar to your own party. For some reason, wild Pokémon don't (This is one reason as to why the Ditto bug exists). Since we are going to need to expand Wild data anyway to account for personality data, would it make sense to make Wild pokémon also load an enemy party similar to trainers, except only the 1st index is used? This would also allow one to free up most data from battle_mon as a bonus, since one can just load such data from the party struct. If one were to do this, the following changes should be made IMO:

old struct: Species, Item, Moves:4, DVs:2, PP:4, Happiness, Level, Status:2 (wait, why is this 2 bytes?), HP:2, MaxHP:2, Atk:2, Def:2, Spe:2, SpA:2, SpD:2, Type1, Type2 (total: 32 bytes)
new struct: LastConsumedItem, Substatus:4, TransformIndex, Type1, Type2, Ability, Rollout, Confused, Toxic, Disable, Encore, Perish, FuryCutter, Protect, Atk, Def, Spe, SpA, SpD, Acc, Eva (total: 24 bytes)

**Comment by ruvaldak** [comment]
What do you mean by "Generate wild and NPC Pokémon? "

**Comment by FredrIQ** [comment]
The Pokémon data structure was changed in 3.0 (this is why it's 3.0 and not, say, 2.4) to incorporate Abilities, Forms and a better Nature implementation. Currently, the Pokémon generation algoritms aren't properly implementing these, meaning that Pokémon always get the same Nature, etc.

**Comment by ruvaldak** [comment]
Ahhh.

Suggestion: It'd be cool to have the character walking animation speed up, or double in speed, when holding B (running). It'd give a bit better indication that the player is, indeed, running. And eye candy. Nostalgic eye candy.

**Comment by roukaour** [comment]
See TODO.md for an up-to-date log.
