### ISSUE TITLE
Pokémon data structure changes

### ISSUE THREAD

**Issue by roukaour** [roukaour/pokecrystal#35]
Since 3.0.0 is going to be a save-breaking update, it's an opportunity to edit the internal data structures.

Goals:
- Separate gender, shininess, natures, and abilities from DVs
- Allow 7 bits for caught level and 8 for caught location
- (less important) Store current HP in the PC, so Nuzlocke mode won't heal by depositing
- (less important) Split the Special IV into SpA and SpD, and add an IV for HP

Possible solutions:
- Just add more bytes. This is very likely to require moving other values in wram.asm to make everything fit in sections. It's also a less convenient size for box_struct, which is currently exactly 32 bytes.
- Get rid of [Pokérus "strains"](http://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9rus#Technical_information) and only use the low 4 bits of PokerusStatus for that (two for days left, 1 as a cured flag). This frees up 4 bits: two for abilities, one for gender, one for shininess.
- Store 1-byte EVs instead of 2-byte stat experience. This uses 6 bytes instead of 10, leafing 4 free: one for more caught data, one for the new IVs, and two for a personality value that determines gender, shininess, nature, and ability. On the other hand, now Pokémon base stats will have to store the EVs they reward. This would take (2 bits/stat) × (6 stats) = 12 bits = 2 bytes. The two "unknown" values could be repurposed for this. Convenient, but I'm really not a fan of EV training. Maybe this could be an internal change, so there's no limit of 510 EVs and the player can treat it just like stat exp.

Edit: Yes, the EV method should work. The stat formula will replace sqrt(StatExp)/4 with EV/4, vitamins will raise an EV by 10 instead of StatExp by 2560, and the change will be transparent to the player (except that EV gain from wild Pokémon will be different if they pay close attention).

Extending the caught data would also provide room to save the ball used. Example:

![Screenshot](http://i.imgur.com/b43J3DD.png)

**Comment by FredrIQ** [comment]
**Capture data**
One byte for location, one for level. 0: Egg, 255

**EVs**
Do you also want to upgrade to EVs fully in that case in how they work? Otherwise you could just make base stats / 64 be added to each EV after battle (Makes EV training faster, but you need to defeat almost 1k Pokémon to max it now with how it wors).

*Upgrading to EVs*
I'm pretty sure you only need one byte: Bitfield for stat to raise (6 bits) and how much to raise it (2 bits, 0-3). I know some give EVs in more than one stat, but do any give different amount to different stats? If 1 is enough, just using up the last padding byte for it should work.

**Result**
1 byte EVs: +5
One EV for SpD: -1 (4)
Capture data stays like now: 0 (4)
SpD+HP DV byte (maintain 4bit DVs): -1 (3)

2 bytes for other data.
*Byte 1*
Bit 15: IsFainted
Bit 14: IsShiny
Bit 13: Ability
Bit 12: Hidden Ability
Bit 11-8: Ball data

*Byte 2*
Bit 7: IsFemale
Bit 6-5: Time of day caught
Bit 4-0: Forms

-2 (1)
One byte goes free. What to do with it?

**Comment by roukaour** [comment]
Yes, some Pokémon give 1 EV in one stat and 2 in another, or even 1 EV in three different stats. And I'd rather switch to the new EV system, whether or not there's a 510 limit. It's more true to the new games, and it avoids weird cases like if all of a Pokémon's base stats are less than 64.

Here's the current data structure:

* 2 bytes: HPExp
* 2 bytes: AtkExp
* 2 bytes: DefExp
* 2 bytes: SpdExp
* 2 bytes: SpcExp
* 1 byte: AtkDefDV
* 1 byte SpdSpcDV
* 1 byte: CaughtData1 (2 bits CaughtTime, 6 bits: CaughtLevel)
* 1 byte: CaughtData2 (1 bit: CaughtGender, 7 bits: CaughtLocation)
* *14 bytes total*

And my plan for 3.0:

* 1 byte: HPEV
* 1 byte: AtkEV
* 1 byte: DefEV
* 1 byte: SpdEV
* 1 byte: SatEV
* 1 byte: SdfEV
* 1 byte: HPAtkDV
* 1 byte: DefSpdDV
* 1 byte: SatSdfDV
* 1 byte: CaughtData1 (2 bits: CaughtTime, 1 bit: CaughtGender, 4 bits: CaughtBall, 1 bit: unused)
* 1 byte: CaughtData2 (8 bits: CaughtLevel)
* 1 byte: CaughtData3 (8 bits: CaughtLocation)
* 2 bytes: Personality (5 bits: nature, 2 bits: ability, 8 bits: gender, 1 bit: unused; low bits reused for shininess) (easy to compare the gender byte against the one in base data)
* *14 bytes total*

**Comment by FredrIQ** [comment]
**EVs**
Fair enough, but there is still just 1 byte needed for EV yield.
Pokémon that raise 2 in one and 1 in another (problematic with my proposed way of adding EV yield data): Venusaur, Butterfree, Togekiss (SpA+2, SpD+1), Beedrill (Atk+2, SpD+1), Parasect, Feraligatr (Atk+2, Def+1), Meganium, Suicune (Def+1, SpD+2), Raikou (SpA+1, Spe+2), Entei (HP+1, Atk+2).

That's 6 spreads that can be special cased by relying on 1111xxxx being an invalid spread (Nothing raises 4 stats). Otherwise, I was thinking to just setup as follows: xxxxxxyy, where each bit in x denotes a stat, and yy denotes how much to raise it (1-3).

Pokémon storage structure EV-wise looks fine

**DVs**
Ok.

**CaughtData**
Why is CaughtGender needed? Mostly everything else looks fine.

**PV**
Did I really forget Nature? Yes I did. Anyway, why 8 bits for gender? You can get away with 2 bits if you define one bit as genderless.
With a 1/1024 rate for shininess, you need to use at least 10 bits for it if you want to compute it on demand, allthough I'd suggest just storing a shiny bit and compute shininess for wild pokémon on generation by randomizing (a=BattleRandom; if a!=0 not shiny; else a=BattleRandom; if a<64 shiny). This also means that you don't end up with shinies not being able to be a certain gender, a certain Unown form, etc. So in the end:
*Byte 1*
2 bits: Ability
5 bits: Nature
1 bit: Shiny

*Byte 2*
1 bit: Gender
1 bit: Fainted
6 bits: Form data (Unowns, Pikachu, Ekans, etc)

Resulting free bytes/bits: 0 bytes, 1 bit (CaughtData1). If desired, 3 additional bits can be freed -- get rid of CaughtGender, have Level and Location be just 7 bits each.

**Comment by FredrIQ** [comment]
As for the interface, wouldn't it be more neat to show a Ball besides the sprite (left of the < arrow in the stats navigation area)? Or are there pallet clashes?

**Comment by roukaour** [comment]
**EVs:** I expect that special-casing those Pokémon would take more code than the 2-byte system. And space isn't an issue, there are already two unused "unknown" bytes.

**CaughtData:** CaughtGender is the OT gender, shown in the stats screen.

**Personality:** Looks OK. Form data is only applicable to Unown and Arbok (good idea there), Pikachu's sprite is determined by its moveset.

**Interface:** Balls use the OW sprite palettes, which are not needed in the stats screen. However, colors are [reused](https://github.com/roukaour/pokecrystal/blob/master/battle/objects/functions.asm#L445), so they'd look better but be ambiguous. I'm not sure which is preferable.

**Comment by FredrIQ** [comment]
**EVs**: Obviously it would be more code, since you'd need a lookup table to handle them, however the difference in complexity is minimal. But if the "unknown" bytes are unused, I suppose one can just use those and change system later if desired.

**CaughtData**: Oh, ok. So 1 free bit which can be made into up to 3 bits free. Not a major difference either way.

**Personality**: While you are right, wouldn't it be easier codewise to make moveset changes change the given form by recalculating the form bits? That way one can use common code to deal with all different forms (and not have to deal with, for example, Pikachu sprite bugs).

**Interface**: Would it be feasible to up the number of available pallets for balls in particular? Also, I think there is a purple pallet available as well which the Master Ball should probably use either way.

**Comment by roukaour** [comment]
Interesting idea to precalculate Pikachu's form like that. I think it could get complicated, though. Two of the forms depend on it belonging to Red or Yellow, and other enemy trainers may have Suurf/Fly Pikachu. So there has to be code *somewhere* that checks the trainer ID and moveset to pick an appropriate form; and the GetVariant routine is a convenient place for it.

As for Balls, there are 8 palette slots, with two used for the battling Pokémon and six for the balls. (The opposing Pokémon's entry gets used because catching it turns the ball that color. I don't know why your own Pokémon has an entry, but there's probably a reason.)

**Comment by FredrIQ** [comment]
Trainer battles load an enemy party similar to your own party (OTPartyMon). For some reason, wild Pokémon don't (This is one reason as to why the Ditto bug exists, since it has to go on the battle_struct for most of its data). Since we are going to need to expand Wild data anyway to account for personality data, would it make sense to make Wild pokémon also load an enemy party similar to trainers, except only the 1st index is used? This would also allow one to free up most data from battle_mon as a bonus, since one can just load such data from the party struct. If one were to do this, the following changes should be made IMO:

old struct: Species, Item, Moves:4, DVs:2, PP:4, Happiness, Level, Status:2 (wait, why is this 2 bytes?), HP:2, MaxHP:2, Atk:2, Def:2, Spe:2, SpA:2, SpD:2, Type1, Type2 (total: 32 bytes)
new struct: Substatus:4, TransformIndex, PP:4 (needed for transform), Type1, Type2, Ability, Rollout, Confused, Toxic, Disable, Encore, Perish, FuryCutter, Protect, Atk, Def, Spe, SpA, SpD, Acc, Eva, LastMove (total: 28 bytes)
...and clean up entries in wram regarding this and move it to battle_struct.

**Comment by roukaour** [comment]
Good idea to move the Filler bytes. It does cause some new bugs:

![](http://i.imgur.com/5PgCPGV.png)

I think just adding Personality data to wild Pokémon separately would be easier for now, and once the feature works it can be refactored to have simpler data structures.

**Comment by FredrIQ** [comment]
Are you seeing the glitched Gyarados only during forced shiny matches? Perhaps it is a matter of shinies in general during these.

**Comment by roukaour** [comment]
That sounds likely. Right now I'm going through all the places that refer to a DV variable and rewriting them to use three bytes (HP/Atk, Def/Spd, SAt/SDf). Which intersects with making other places depend on a Personality value (Shiny/Ability/Nature, Gender/Fainted/Form), so this will probably get fixed as a result.

**Comment by FredrIQ** [comment]
In 2.0, shiny rate is 1/1024. Did you intend to change this to 1/4096? Because a comment about Shiny Charm references a 3/4096 rate (technically 1-(4095/4096)^3 but that's nitpicking...), which would mean a shiny rate of 1/4096.

**Comment by roukaour** [comment]
Yes, I mean to copy Gen VI's rates.

Check out the newdvs branch. It's in-progress to use those three new bytes (third DV and personality). Here's what hasn't been updated yet:

* engine/breeding/egg.asm
* event/daycare.asm
* event/stats_judge.asm
* engine/stats_screen.asm:TN_PrintCharacteristics

(Although it's still quite buggy. engine/move_mon.asm:GeneratePartyMonStats creates a corrupt Pokémon, and even when I comment out its code and hard-code a correct Pokémon structure, loading the bytes into [hli] one by one, there are further bugs on the stats screen and in battle, such as the displayed nature changing when experience is gained.)

**Comment by FredrIQ** [comment]
How did that break exactly? DIdn't it work fine when all that was done was to move filler bytes around? Because it sounds like something was broken not as a direct effect of changing the structure then...

**Comment by roukaour** [comment]
"git diff master..newdvs" looks pretty straightforward. Things like GetVariant operating on MonForm (MonPersonality2) instead of MonDVs, GetAbility operating on MonAbility (Personality1) instead of MonDVs, copying 3 DV bytes (and sometimes 2 subsequent personality bytes) instead of 2... move_mon.asm is suspicious because it's a long routine with many jumps and stack operations, I made a lot of edits, and might have gotten some offsets wrong. Also I looked for places to edit by searching for "DV", so if there's some place that accesses them via pointer assumptions and doesn't have a helpful label or comment about DVs, I'd have missed that.

**Comment by roukaour** [comment]
Recording debugging progress here for now. Went through every changed line in the newdvs branch; [here's a diff](http://pastebin.com/3sg11bMk) of what might be buggy.

* **engine/move_mon.asm:** a few routines are complex enough to be automatically suspicious
* **battle/core.asm:** roaming mon code (untested)
* **event/bug_contest_judging.asm:** `ContestScore` (probably correct, but long and untested)
* **battle/effects/transform.asm:** `BattleMonStats - BattleMonPP` → `BattleMonStats - BattleMonPersonality` (probably correct, but untested)
* **gfx/load_pics.asm:** `GetVariant` for Pikachu (probably correct, but untested)

engine/move_mon.asm definitely has a bug in TryAddMonToParty/GeneratePartyMonStats, since hard-coding it to generate a certain Pokémon works. But there are other bugs of omission, not addition, since like I said gaining experience seems to corrupt the personality value and change things like natures and shininess. Which is probably caused by a section that I haven't updated yet, not a line that I edited incorrectly.

**Comment by FredrIQ** [comment]
Yeah, I figured the exp corrutping PV bug was from stat exp. I coded a new EV gain function yesterday but it's unfinished (it's not checking Poké Rus, Macho Brace or power items that I intended to add code for), and it also ended up messier than I liked it. It also needs testing..

I saw that you commented out Stat Exp gain, which will end up conflicting with my changes, allthough it should be a trivial merge.

**Comment by roukaour** [comment]
Fixed most of the problems with move_mon.asm. NPC trainers have incorrect HP and possibly other stats, but your starter looks entirely correct. Still needs further testing to be sure.

**Comment by SadisticMystic** [comment]
EV yields could be coded as follows:
-if the first six bits contain exactly one 1, then that signals a stat, and the last two bits are a straight binary number to denote how much to raise it by
-if they contain three 1s, then that signals three stats, and there's obviously only enough room to allot 1 EV to each of them, so the last two bits can be completely ignored
-if they contain two 1s, then there are three possible cases: it awards 2 EVs with 1 to each stat (signalled by 00 in the final two bits), it awards 3 with 2 going to the stat that's earlier in reading order (signalled by 10), or it awards 3 with 2 going to the second stat in order (signalled by 01).

This is enough for all possible yields to cleanly fit in a single byte, with no need for "invalid header = fall back on a lookup table" logic.

**Comment by roukaour** [comment]
That's possible, yes, but with two unused bytes already there it's simpler to just use (2 bits/stat) * (6 stats). No branches, just a loop from 1 to 6 that adds to each stat.

**Comment by FredrIQ** [comment]
A bit late now perhaps, but something I have always felt to be a bit silly is how PP is stored in the "primary" structure (the part that is always there). Would it be feasible to remove the part that isn't the PP Up data (and possibly move said data to a single byte) and use the other 24 bits (possibly 3 bytes if the PP up data is moved to a single structure) for other stuff? For example, 5bit IVs (requires 1 additional byte), 32bit PV (requires 2 bytes), extending the move table to 510 moves (requires 4 bits).
