### ISSUE TITLE
Battle Tower data needs revision

### ISSUE THREAD

**Issue by roukaour** [roukaour/pokecrystal#69]
All that needs to be stored is: {species, item, moves, personality}

* level = wBTChoiceOfLvlGroup × 10
* EVs = wBTChoiceOfLvlGroup × 25 for each (unfair to have max EVs at low levels)
* DVs = 255 each
* happiness = 255
* OT ID, Pokérus, caught data, status = 0
* Call FillPP for PP, CalcPkmnStats for stats, CalcExpAtLevel for experience, GetPokemonName for nickname (already done, overwrites the nickname from data)

Advantage: instead of choosing from 21 Pokémon per level group, the entire set of 210 (or more) is available. And editing them is much easier.

**Comment by FredrIQ** [comment]
Could use the wonder trade whitelist to determine when evolutions are invalid and avoid underleveled evolved mons from showing up.

Also, should be EV * 28, this makes level 90 and 100 have perfect EVs and also makes stat progression more even.

Another option is to make EVs and DVs start at (level group)*10+2 and (level group) and increase by 10 and 1 respectively for each defeated trainer in a row. This makes it so that once you defeat 15 trainers in a row (2 full rounds + 1 trainer), you get max EVs and DVs from then on. Could also make it so that, independently per thing, each mon has a (100-streak*7)% chance of having a random non-hidden Ability, no item, random Nature and an ordinary level-up moveset. This means that you can do OK with just a "casual" in-game team but may not be able to get too far with it.
