### ISSUE TITLE
Muk's Toxic prints "It doesn't affect Mewtwo!" for a Mewtwo with Insomnia

### ISSUE THREAD

**Issue by roukaour** [roukaour/pokecrystal#84]
Possibly Insomnia is preventing Poison as well as Sleep?

**Comment by FredrIQ** [comment]
If that was the case, it would also print something like "Mewtwo's Insomnia activated!".

I'm away atm and can't check this properly until next week, so feel free to do it you.

**Comment by roukaour** [comment]
Aura Sphere (Fighting) prints "It's super-effective!" against Tangela (Grass).

Looking at battle/type_matchup.asm, right after the FIGHTING entries is "db POISON, GRASS, SUPER_EFFECTIVE".

Not going to debug this myself, since you're already working on the general area, but it's suggestive. Possibly one of the places that looks up in this table (I see there are multiple copy+pasted ones, not a single routine that gets called) doesn't stop when the attacking type is over?

**Comment by FredrIQ** [comment]
When I have performed battle tests lately with various teams, it seems that damage calculations still seem to be correct. I can be totally wrong here, but it's possible that the type effectiveness byte is screwed up somehow along the way.

**Comment by roukaour** [comment]
TypeModifier's neighbors in WRAM are CurOTMon and wBattleParticipantsNotFainted before, and CriticalHit and AttackMissed after. I don't think any of them have been modified recently or would overflow to affect it, they're all simple 1-byte values.

Have you noticed any pattern in which messages get printed?

**Comment by FredrIQ** [comment]
0x messages no longer seem to print properly, instead saying the attack missed (Presumably for similar reasons as to how 1gen messages worked).

**Comment by roukaour** [comment]
If you discover a fix for this, can you factor out the type modifier lookup into its own routine? Apart from being neater code, it would make implementing Inverse Battles possible (I'm thinking of an alternate mode in the Battle Tower).

**Comment by FredrIQ** [comment]
I think I might have found the issue, it seems like there is a potential stack overflow for CheckTypeMatchup vs CheckNullificationAbilities (volt absorb, etc), because they seem to call each other. Oops.
Found this when implementing Damp. I'll implement Damp anyway but look into how I can fix this properly afterwards. The reason this issue crept up is that I wanted to not mess with the AI but still allow it to understand stuff like Levitate, since it already uses type matchup checking, but also need to take into account that type immunities override immunities caused by abilities (this matter for e.g. Lightningrod on ground types).

**Comment by FredrIQ** [comment]
Does this still happen with the fix?

**Comment by roukaour** [comment]
This no longer happens.
